# Mouvement des Corps Rigides
## KIN-6839

### Rototrans dans biorbd

In [1]:
# Import needed packages
import biorbd    as brbd
import numpy     as np
import BiorbdViz as brbdv

In [2]:
# Load a simple model
b = brbdv.BiorbdViz(model_path="../data/2boxes.bioMod")
# Play with it
b.set_q(np.array([1,0,0,np.pi/2,0,0,0,1,0,0,0,0]))

Note : biorbd's interface uses Euler angles. Look at the .bioMod file to find the corresponding sequence. Inside biorbd, rototrans are used, as seen during the class. Let's play a bit with these notions. 

In [3]:
# Code a function which takes a rototrans and outputs 6D vector of configuration [trans,eul]
# Hints : 
# brbd.RotoTrans.toEulerAngles => <function biorbd.biorbd.RotoTrans.toEulerAngles(rt, seq)>
# brbd.object.to_array() => numpy array of the biorbd object
# np.hstack, np.vstack => horizontally or vertically stacks numpy arrays

def rt_to_config(rt) :
    ...
    return ...


Test the function.

In [4]:
rt = brbd.RotoTrans()
print(f"Identity transform : \n {rt.to_array()}")
print(f"Equivalent coordinates : \n {rt_to_config(rt)}")

Identity transform : 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Equivalent coordinates : 
 [ 0.  0.  0. -0.  0. -0.]


Now, let's play with our boxes.
Build a rototrans matrix "rpz" for Rot(z,90°).
Build a rototrans matrix "rny" for Rot(y,-90°).

In [5]:
#rpz = brbd.RotoTrans(np.matrix([[0,-1,0,0],[1,0,0,0],[0,0,1,0],[0,0,0,1]]))
rpz = ...
rny = ...
rpz_config = rt_to_config(rpz)
rny_config = rt_to_config(rny)
b = brbdv.BiorbdViz(model_path="../data/2boxes.bioMod")
b.set_q(np.hstack([rpz_config,rny_config]))

Test the product of rototrans, as seen in class. Visulalize the result in the viewer. Try to left and right multiply, discuss.

In [ ]:
###Code

### Rappels d'intégration numérique

Intégrer une fonction mathématique peut se faire analytiquement (formules connues, IPP, etc.) ou numériquement. 
Le principe de base de l'intégration numérique repose sur des appels à la fonction que l'on cherche à intégrer.

Coder la méthode des rectangles (Euler).
Tracer la fonction et les rectangles superposés.
Comparer à la valeur analytique connue en faisant varier le pas d'intégration.

In [6]:
import matplotlib.pyplot as plt
from time import time

xmin = 0
xmax = 100
nbx = 1000
nbi = nbx - 1 # nombre d'intervalles

x = np.linspace(xmin, xmax, nbx)
y = np.cos(x)
plt.plot(x,y,"bo-")

integrale = 0
t = time()
for i in range(nbi):
    integrale = ...
    # dessin du rectangle
    x_rect = ... # abscisses des sommets
    y_rect = ... # ordonnees des sommets
    plt.plot(x_rect, y_rect,"r")
    
print("temps nécessaire :", time() - t)
print("intégrale numérique =", integrale)
print("intégrale exacte = ",np.sin(xmax))

plt.show()

temps nécessaire : 1.4254205226898193
intégrale numérique = -0.49905180657145
intégrale exacte =  -0.5063656411097588


Coder la méthode des trapèzes (Euler).
Comparer à la valeur analytique connue en faisant varier le pas d'intégration.

In [6]:
nbx = 1000
nbi = nbx - 1 # nombre d'intervalles

x = np.linspace(xmin, xmax, nbx)
y = np.cos(x)
plt.plot(x,y,"bo-")

integrale = 0
t = time()
for i in range(nbi):
    integrale = ...
    # dessin du rectangle
    x_rect = ...] # abscisses des sommets
    y_rect = ... # ordonnees des sommets
    plt.plot(x_rect, y_rect,"r")
    
print("temps nécessaire :", time() - t)
print("intégrale numérique =", integrale)
print("intégrale exacte = ",np.sin(xmax))

plt.show()

temps nécessaire : 1.5310637950897217
intégrale numérique = -0.5059427539043958
intégrale exacte =  -0.5063656411097588


Lire d'autre méthodes d'intégration (Simpson, pôlynomes de Lagrange).
Utiliser l'intégration RK45 de scipy et comparer aux méthodes précédentes.

In [10]:
from scipy import integrate

def mycos(t,y):
    return np.cos(t)

t = time()
sol = integrate.solve_ivp(...)

print("temps nécessaire :", time() - t)
print("intégrale numérique =", sol.y[0][-1])
print("intégrale exacte = ",np.sin(xmax))


temps nécessaire : 0.007107973098754883
intégrale numérique = -0.5060210157655309
intégrale exacte =  -0.5063656411097588


### Retour aux corps rigides 

Intégrer une vitesse de rotation spatiale avec RK45. 
Comparer à la formule de Rodrigues.
Tracez l'erreur en degrés en fonction de la durée d'intégration.
Visualisez le résultat.

In [15]:
import math as math
from scipy import interpolate

T = 2.654*2*np.pi # Durée de la simulation
w = [1,1,1] # Axe de la rotation
w /= np.linalg.norm(w)

def so3(x):
    return ...

def R_dot(t,R,w):
    ...
    return ...


func_ode = ...

R_0 = np.reshape(np.eye(3),9)
sol = integrate.solve_ivp(...)
sol_interp = interpolate.interp1d(...,kind='cubic')

print("intégrale numérique =", np.reshape(sol.y[:,-1],(3,3)))

def rodrigues(w,T):
    return ...
int_rod = rodrigues(w,T)
print("intégrale exacte = ", int_rod)

def rot_to_eul(rot):
    #Attention, vérifier la séquence d'Euler dans le modèle
    ...
    return np.array([psi,theta,phi])

# Convertir la matrice de rotation interpolée en Euler
eul_interp = []
interp_ratio = 1000
t_interp = np.linspace(0,T,interp_ratio)
for t in t_interp :
    ...

# Pour 200 temps d'intégration de 0 à 2000 secondes calculer l'erreur commise par l'intégration numérique 
# par rapport à la formule de Rodrigues.

Ts = np.linspace(0,2000,num=200)
err = []
err_eul = []
for T in Ts :
    ...

intégrale numérique = [[-0.04280153  0.99781699  0.04498453]
 [ 0.04498453 -0.04280153  0.99781699]
 [ 0.99781699  0.04498453 -0.04280153]]
intégrale exacte =  [[-0.04484597  0.99788975  0.04695622]
 [ 0.04695622 -0.04484597  0.99788975]
 [ 0.99788975  0.04695622 -0.04484597]]


A présent, un petit exercice de présentation de résultat avec la librairie matplotlib.
Afficher sur une première figure le résultat de l'interpolation en angles d'Euler.

Sur une seconde figure, afficher deux graphiqueas : un pour l'erreur matricielle commise par RK45 et l'autre pour l'erreur correspondante en angles d'Euler.
Discuter.

In [16]:
import seaborn as sns
sns.set()

plt.figure()
plt.plot(t_interp,eul_interp)
plt.xlabel("xlabel")
plt.ylabel("ylabel")
plt.title("...")

fig,(ax1,ax2) = plt.subplots(1,2)
...
ax1.set_title("Frobenius norm of the error on the final orientation matrix \n as a function of the simulation duration",x=-0.3)
...
ax2.set_title("Norm of the error on the final euler angles \n as a function of the simulation duration",color=[1,0,0])
fig.suptitle("Whatever",fontsize=56)
plt.show()

Animer la sous biorbd-viz.

In [70]:
q_brbd = ...
b = brbdv.BiorbdViz(model_path="../data/2boxes.bioMod")
b.load_movement(q_brbd.T)
b.exec()

Refaire la même analyse avec des rototrans.

In [ ]:
###Code

### Cinématique avec biorbd
Tester la cinématique d'une chaine avec biorbd.

In [82]:
b = brbdv.BiorbdViz(model_path="../data/robot.bioMod")
b.exec()

Envoyer des séquences d'angles aléatoires mais continues à biord-viz et constater le résultat de la cinématique directe appliquée à la chaîne.

In [16]:
nb_frames = 1000
angles = np.zeros((3,nb_frames))
for i in range(nb_frames-1) :
    ...
b = brbdv.BiorbdViz(model_path="../data/robot.bioMod")
b.load_movement(angles.T)
b.exec()

### Dynamique avec biorbd
Tester la dynamique de la chaîne : effectuer une simulation, la gravité est prise en compte par défaut dans les équations !

Écrire un programme rapide avec une intégration de type Euler.

Tracer la trajectoire du centre de masse.

In [54]:
m = brbd.Model("../data/robot.bioMod")
angles = np.zeros((3,nb_frames))
coms = np.zeros((3,nb_frames))
q  = np.zeros((3,))+0.01
dq = np.zeros((3,))
tau = np.zeros((3,))
dt=0.01
coms[:,0] = m.CoM(q).to_array()
angles[:,0] = q

for i in range(nb_frames-1) :
    ...
    
b = brbdv.BiorbdViz(model_path="../data/robot.bioMod")
b.load_movement(angles.T)
b.exec()
# Trajectoire du CoM
plt.plot(...)
plt.title("CoM trajectory of a free falling triple pendulum")
plt.xlabel("$COM_y$")
plt.ylabel("$COM_z$")

Text(0, 0.5, '$COM_z$')

Recommencer avec RK45.

In [ ]:
###Code

Jouer avec les paramètres de la simulation, changer les paramètres inertiels, ajouter des couples articulaires, etc...

In [ ]:
###Code

Utiliser le modèle biorbd "robot_with_markers". Ce modèle inclut un marqueur au bout de chaque corps de la chaîne cinématique. 
Écrire une fonction qui calcule les positions 3D de ces marqueur, sachant q, la configuration du robot. 
Tracer les trajectoires de ces marqueurs pendant la simulation précédente.

Indice : biorbd.Model.globalJCS(q,i) => Rototrans du segment i dans le repère global, pour la configuration q

In [66]:
m = brbd.Model("../data/robot_with_markers.bioMod")

def apply_rototrans_on_vec(rt,vec) :
    ...
    return ...

robot_markers = np.zeros((3,m.nbSegment()))
for i in range(m.nbSegment()) :
    robot_markers[:,i] = m.marker(i).to_array()
 
markers_traj = np.zeros((m.nbSegment(),3,nb_frames))

...

plt.plot(markers_traj[0,1,:].T,markers_traj[0,2,:].T,'rx')
plt.plot(markers_traj[1:,1,:].T,markers_traj[1:,2,:].T)
plt.title("Markers trajectories of a free falling triple pendulum")
plt.xlabel("$Y ~coordinate$")
plt.ylabel("$Z ~coordinate$")

(4, 1000)


Text(22.097222222222214, 0.5, '$Z ~coordinate$')